In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/README.roboflow.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/data.yaml
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20230803-WA0043_jpg.rf.4a7fc25d63094df1086c937530be065d.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20230817-WA0059_jpg.rf.210346fc4ef7aea8139cff0f27886636.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/augmented_topbasi-28-_jpg.rf.3854f3fef56e150116c9d5516c7442a2.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20230914-WA0088_jpg.rf.e655a0b26db44ce2b40be13469bc8c5d.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20230907-WA0045_jpg.rf.48a404f5f38ea62ebf3879f73bd18a3e.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20230808-WA0040_jpg.rf.e8e8409906f716856ea50b371f8d20f7.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/augmented_topbasi-4-_jpg.rf.c6f343dcda7b46b035145df60fd87bc9.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG_20230712_101450_jpg.rf.6a74b2e10ad051fde3012ef81f843e5d.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20230914-WA0063_jpg.rf.9f3498ceedcf34645de4cd3acca28a5c.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20230818-WA0104_jpg.rf.d00d21aa6ada14c8d154dfa9eacc5521.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/augmented_a00011_jpg.rf.c03215936fd7b37dc8fd4374275c5651.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20231003-WA0033_jpg.rf.0aab10674e38a22758d9a495f20773b1.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20230818-WA0052_jpg.rf.5455510ba254316727f8d93d8bbbc35f.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/006679_jpg.rf.9722b7c48a9b800a742fd471db33a8db.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20231017-WA0054_jpg.rf.e6553e81675e7fd628479665400fefd8.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/20230719_104130_jpeg_jpg.rf.da1078c6a57601e9e29404d3e5c45373.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/Snapchat-944358305_jpg.rf.dc65f12e7b86b8c678cf44e821aaa30d.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20230920-WA0063_jpg.rf.5faf205c75eca19aa9703cad57272904.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20230906-WA0067_jpg.rf.3bf350eb0998655943c1028df0a3eed6.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/20230719_122926_jpeg_jpg.rf.235f3eb43141b8c3ba8c699d166605b2.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/006874_jpg.rf.28e03710e312ec9d62ce9213cb415bc2.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20231003-WA0030_jpg.rf.5bed9a6cd963f76ef307c799e81cb031.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/20230719_141054_jpeg_jpg.rf.cee93591c34a7ee531dec215712ca534.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20230809-WA0076_jpg.rf.9588a0e6e1e7a22e433a86bc79e3e6af.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG_20230823_112835_jpg.rf.022a19a5df785edff4a9a6d6f1bb8675.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20231012-WA0072_jpg.rf.11ce41c8df62fd63e049427a3b5765ee.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/006898_jpg.rf.a53ac895e012cd024a0e303205e4af4f.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20231014-WA0037_jpg.rf.2d14afc9b188d3debd9fb7a9166fb395.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20230915-WA0027_jpg.rf.09a4515506b84e6834c8b06f66b20f49.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/WhatsApp-Image-2023-09-04-at-9-56-27-AM-1-_jpeg_jpg.rf.b6d449abb7fbd0d9499c848852525826.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20230907-WA0019_jpg.rf.703f3de714c558becd46b4e11b0489ec.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/Snapchat-1139889284_jpg.rf.0a26ac221f8c54672e7ae694f6e49901.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/006861_jpg.rf.2bba3952d2019ba9bda1f626884032f8.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20230907-WA0045_jpg.rf.acddba05211e8339068eec00b6f65020.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/1318_jpg.rf.1a42fe521da7baa413a9eadeb58f42f4.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20230927-WA0008_jpg.rf.39587481d7d3b6a74acff135b292153a.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20230914-WA0071_jpg.rf.4d9df6ba6bc941bb6f7cc01ea85a76fe.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20230920-WA0185_jpg.rf.4aa3cec8238cb8bc4970b845ec39bc42.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20230914-WA0026_jpg.rf.8cba2f36410bea340ae0f611d046515d.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/augmented_topbasi-27-_jpg.rf.5a01777a8040bb4d89c69199ce4f763d.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20230818-WA0065_jpg.rf.4253f9e85641d7b8af9517b8853d1c24.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20231012-WA0002_jpg.rf.53a186dea955ee8b8e310ab908d068a5.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20231010-WA0077_jpg.rf.2e48cf3c26a50cc3033d88d3acc8be18.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20231017-WA0041_jpg.rf.40e24942fa95138bf3c2665cadd61fce.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20230818-WA0064_jpg.rf.747429769e139c1f1d89547bbbe8462e.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG_20230823_123713_jpg.rf.13739379ec65d8c31efac40f1b8d8210.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20230808-WA0043_jpg.rf.e94cf0878be7541c97aefa9f1c519614.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/welspun_15657249776829_png_jpg.rf.1e10c0c886dc9897848667a30bb952cd.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20230817-WA0060_jpg.rf.303225d63c233dcac5011c1ac3947fd3.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG_20230727_114152_jpg.rf.77a0aac9117745acf980e99d2c638215.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/WhatsApp-Image-2023-09-04-at-9-56-35-AM_jpeg_jpg.rf.0cf01e57a1511cf1ce72f23220d6d820.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20230920-WA0055-1-_jpg.rf.5482211a30f87892bafdf1d95290eaf6.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20230920-WA0055-1-_jpg.rf.844a3c7701e0a8c174cff455f19861fa.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20230914-WA0051_jpg.rf.92ee3544f540d9d20536c3225f4441e4.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20230803-WA0046_jpg.rf.d83ebfd2f5ce2a8dba7de93bb4950d5a.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG_20230727_143803_jpg.rf.f4d003245ef36ace0bda11da63ced480.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20230914-WA0074_jpg.rf.ae537ff9747384cd9b5a783f830d3140.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20231012-WA0043_jpg.rf.1daaa0d93b90fd75ac1fbd026c20c5d9.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20230817-WA0092_jpg.rf.cc1456eae16cf2955149cc4aa654c991.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20230907-WA0019_jpg.rf.1fb69bcc819a5079d707987fce70d0a0.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG_20230727_143803_jpg.rf.53da503001d0b0413363d26cfa940b6c.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20231012-WA0072_jpg.rf.6c91e94f26d0f694d92671c49f62b406.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/WhatsApp-Image-2023-09-04-at-9-56-30-AM_jpeg_jpg.rf.d28bed30189defc5172915450ffb989a.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/topbasi-28-_jpg.rf.8bf4b2b411fb5e760b625ccd12296fce.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG_20230823_110759_jpg.rf.8510c9ca784a2473bd06b70fb50a1360.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20231014-WA0007_jpg.rf.34b2f0325fc52caf265d027491b82548.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/20230719_140834_jpeg_jpg.rf.3c1cc2f2351f4a4965492929a4471dd4.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/20230719_103719_jpeg_jpg.rf.d4edc50d62895654b2602cd3dad8267e.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/Fab_20231004_115921_jpg.rf.4c505c986b38adc5295af183e3551e5e.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20231014-WA0037_jpg.rf.4ca2539b55b2086648c7edcc19d1b6d8.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/augmented_topbasi-20-_jpg.rf.1fb50cc9243e8e9b466b1f63ee3eed18.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/20230719_152654_jpeg_jpg.rf.527d8db0f5da960702894c13178e351a.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/Snapchat-1750891373_jpg.rf.da5003806fc0804659ebdd7b7ed4d9a4.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20230803-WA0044_jpg.rf.25be0d4594adbdacc37a0098ca28b730.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/20230719_121704_jpeg_jpg.rf.1143eefabfea46e08293ace04f0fa800.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20230906-WA0087_jpg.rf.7262b837e277ff5c74e015c66023ea08.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20230818-WA0045_jpg.rf.4320ce33fe63daad0e7bd3042e00e007.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20230926-WA0023_jpg.rf.559b5004cfbe8845e89364199051abc1.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/augmented_Fabric5_jpg.rf.c04ae1ab47c227a4e0f7aebe6c74a4b6.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20230924-WA0071_jpg.rf.42d9c9e0ba4b7e5aa3627309f89c4b29.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/20230718_114333_jpeg_jpg.rf.505742c3ee315eb19e8350fe6535c9e2.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG_20230823_124025_jpg.rf.2e19a7cc4f9d0439fe7b9ab4bb43a024.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20231006-WA0040_jpg.rf.c92b2773f82e8a7e3c9f5014148e6109.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20230816-WA0027_jpg.rf.6686ed5f0f428a963081c0ca166d71a1.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/augmented_welspun_166742126855702_png_jpg.rf.0a6450857172e04b2be21986bdaea7d6.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/WhatsApp-Image-2023-09-04-at-9-56-34-AM-1-_jpeg_jpg.rf.bef82418f3dfa668772e34448e15ac8d.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/Snapchat-944358305_jpg.rf.1d88349084ddf51247398816c8cc932b.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20230817-WA0081_jpg.rf.9402e0409f930a8485fb9cfcb55fbe63.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20231006-WA0031_jpg.rf.2040daa180d1e8a044e2572170515fea.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG_20230824_110838_jpg.rf.c2a6d37a5f4fd387dd1fb2c17b385732.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20230914-WA0048_jpg.rf.01d15232f28d2318e5e33c9459b498f2.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/20230719_103719_jpeg_jpg.rf.8837966c1509645b9e7b1993b32d3ed3.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20230817-WA0060_jpg.rf.4b2e7de9b7bdcabd5272a153c0baece6.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20231009-WA0019_jpg.rf.b65b9ea86e231aba537f2abc24e25b06.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/20230719_101243_jpeg_jpg.rf.f0e15e1c95a361a0421d46e4ebb66e0b.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20230818-WA0058_jpg.rf.a832ec8c9a92ef875e63bd6c7e1e6264.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20231017-WA0058_jpg.rf.17bf31d023c17928c9f79f390a335e05.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20231003-WA0050_jpg.rf.29b4a5a29165b5fe07eb02f993f2c75e.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/WhatsApp-Image-2023-09-04-at-9-56-29-AM-2-_jpeg_jpg.rf.d8e71a77ba80b4ee602380377da99cf1.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20230803-WA0048_jpg.rf.a7406be5e024300a09ad2f295bbdd251.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20231009-WA0043_jpg.rf.7cdd4b9661917c930b36813d1bfaa2b1.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20230817-WA0085_jpg.rf.6db3b706fd48d0f368c871d0ac8e39f1.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20230906-WA0054_jpg.rf.12904557b98ba6d50e7462d244377984.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20231014-WA0004_jpg.rf.42fb05fffd138b9ca1a97ad3e9e90726.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20231003-WA0039_jpg.rf.c81b4c5a96fdc2ab22f511f2922cec8f.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20231003-WA0040_jpg.rf.a2c49ad5b18705099abdcd9963f97b4d.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/20230712_141549_jpeg_jpg.rf.cc4b6487cbeda31db402cd1c020c5354.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20231009-WA0049_jpg.rf.51697224865067e6a3bb2ff9c97a678d.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/20230719_104130_jpeg_jpg.rf.d3e4073e8f9cc875e2e37958879069af.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG_20230727_150230_jpg.rf.86b3defdb01acdf3eabd8e272f2d80fe.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20230818-WA0066_jpg.rf.73cfd9dfc9d03087a163c426d7e22894.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20230808-WA0045_jpg.rf.0168f2a4f05743210687d16351e77bde.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/WhatsApp-Image-2023-09-04-at-9-56-20-AM-1-_jpeg_jpg.rf.6dafa3e7785b3402afc1110d3013c393.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/20230712_141333_jpeg_jpg.rf.250f20f6b071812f300bbaca1b1d377e.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20231012-WA0036_jpg.rf.0d539dd019aa8e660213eb0cc7a6c4ec.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG_20230823_124025_jpg.rf.903d29d1020ade0dce6260eed5dc528e.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG_20230823_123945_jpg.rf.baa9d95b6a215805872c33e51ff70991.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/WhatsApp-Image-2023-09-04-at-9-56-25-AM-2-_jpeg_jpg.rf.e6b13029739b069c09df58d63a15c4ff.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20231014-WA0020_jpg.rf.ef146ca00afdab9c7fa574b40608b5d0.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/Snapchat-1750891373_jpg.rf.efeff3eb9f82ca3d508426f155c7dbe2.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG_20230824_114759_jpg.rf.383fa2f6e3a7468f33f1e6e991ed598a.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20230906-WA0067_jpg.rf.6b043aac45a259f5f1fd0a82ba2073a1.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20230818-WA0083_jpg.rf.1df59a15d54cc18ea97633a5fc5e28b5.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG_20230824_114750_jpg.rf.f76621a0cdb8f900028331179f488bcc.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20231017-WA0043_jpg.rf.c506d827252489db9e405dd59fcb7d3e.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/20230719_121612_jpeg_jpg.rf.a1097dc12e8bc5ce334f7599875f2a0c.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/WhatsApp-Image-2023-09-04-at-9-56-23-AM-1-_jpeg_jpg.rf.8123db9b3612e3cf2e0788bd7ad75cce.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/augmented_topbasi-14-_JPG_jpg.rf.ea7a159897bc1716c4d110a742083199.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/20230719_122926_jpeg_jpg.rf.3c09cf2c4ca75027f62a35f8df40671d.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG_20230823_112903_jpg.rf.9a792afc02202cc71bf795da95b03d5e.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20230817-WA0078_jpg.rf.b2868c292f08ee396a5d670376809a37.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20230807-WA0027_jpg.rf.6bc6eb41dfe7c12d1ad83e5be35d7c3b.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20231006-WA0033_jpg.rf.3fdedfc30807f25525bb84e090382aa5.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20230818-WA0079_jpg.rf.61359b0799f867f60602fb6fef251518.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG_20230823_105842_jpg.rf.cc62aee7f08c64d93e785df956070086.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20231010-WA0082_jpg.rf.2022305795075bfe598688321025d7f6.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20230817-WA0076_jpg.rf.2467914658d1e4e83426d8587e994625.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/20230718_101432_jpeg_jpg.rf.7189e7b8246a0d910cba2dc5ae240129.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20230926-WA0023_jpg.rf.5bfc6006101551b629289c5af699fe68.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20230809-WA0065_jpg.rf.093f90e950f3a5cd40c50075c00561ec.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/20230719_101243_jpeg_jpg.rf.b80852f52e7b4754326e14ac3c813e96.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20231003-WA0052_jpg.rf.e2a67a82c0939afae087180cc90154a4.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20230921-WA0034_jpg.rf.7e75ed12751812fa5657a4fc871ff651.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20231006-WA0075_jpg.rf.692b6510d92f9c16ae1728d909b663c4.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG-20230809-WA0083_jpg.rf.a8c14433d80a45a2348b519a650a3dfa.txt
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/valid/labels/IMG_20230823_110529_jpg.rf.f47bbaec2be32f3ecc4d19b1edc2ae38.txt

In [3]:
# ============================================================
# CELL 1 — INSTALL + GPU CHECK
# ============================================================

!pip install -q ultralytics pyyaml

import os
import sys
import time
import shutil
import yaml
import json
import glob
from pathlib import Path

import torch
import pandas as pd

assert torch.cuda.is_available(), (
    "GPU is required. Go to Kaggle -> Settings -> Accelerator -> GPU"
)

print("GPU:", torch.cuda.get_device_name(0))
print("PyTorch:", torch.__version__)

from ultralytics import YOLO
from ultralytics.utils.torch_utils import get_flops

print("Ultralytics:", "OK")

GPU: Tesla T4
PyTorch: 2.11.0+cu128
Ultralytics: OK

In [25]:
# ============================================================
# RESTORE EAF MODULE
# ============================================================

from pathlib import Path

CODE_DIR = Path("/kaggle/working/E_EAF_YOLO11n/code")
CODE_DIR.mkdir(parents=True, exist_ok=True)

eaf_code = r'''
import inspect
from pathlib import Path
import torch
import torch.nn as nn
import yaml
import ultralytics.nn.tasks as tasks
import ultralytics.nn.modules as modules


# 1. Efficient Channel Attention
class ECA(nn.Module):
    def __init__(self, c1=None, c2=None, k=3):
        super().__init__()
        kernel = 3

        if isinstance(c1, int) and c1 in (3, 5, 7):
            kernel = c1
        elif isinstance(k, int) and k in (3, 5, 7):
            kernel = k

        self.avg_pool = nn.AdaptiveAvgPool2d(1)

        self.conv = nn.Conv1d(
            1,
            1,
            kernel_size=kernel,
            padding=(kernel - 1) // 2,
            bias=False
        )

        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        y = self.avg_pool(x)

        y = self.conv(
            y.squeeze(-1).transpose(-1, -2)
        ).transpose(-1, -2).unsqueeze(-1)

        return x * self.sigmoid(y)


# 2. Attentional Feature Fusion
class AFF(nn.Module):
    def __init__(self, in_channels, out_channels=None):
        super().__init__()

        if isinstance(in_channels, int) and out_channels is None:
            out_channels = in_channels
            in_channels = [in_channels, in_channels]

        elif isinstance(in_channels, int) and isinstance(out_channels, int):
            in_channels = [in_channels, out_channels]

        self.out_channels = out_channels

        self.conv_adapters = nn.ModuleList([
            nn.Conv2d(c, out_channels, 1, bias=False)
            if c != out_channels else nn.Identity()
            for c in in_channels
        ])

        mid = max(out_channels // 4, 16)

        self.conv1 = nn.Conv2d(
            out_channels,
            mid,
            1,
            bias=False
        )

        self.bn1 = nn.BatchNorm2d(mid)
        self.relu = nn.ReLU(inplace=True)

        self.conv2 = nn.Conv2d(
            mid,
            out_channels,
            1,
            bias=False
        )

        self.bn2 = nn.BatchNorm2d(out_channels)

        self.global_pool = nn.AdaptiveAvgPool2d(1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, xs):

        if not isinstance(xs, (list, tuple)):
            xs = [xs]

        x0 = self.conv_adapters[0](xs[0])

        x1 = (
            self.conv_adapters[1](xs[1])
            if len(xs) > 1
            else x0
        )

        x_sum = x0 + x1

        loc = self.bn2(
            self.conv2(
                self.relu(
                    self.bn1(
                        self.conv1(x_sum)
                    )
                )
            )
        )

        glo = self.bn2(
            self.conv2(
                self.relu(
                    self.bn1(
                        self.conv1(
                            self.global_pool(x_sum)
                        )
                    )
                )
            )
        )

        weight = self.sigmoid(loc + glo)

        return x0 * weight + x1 * (1.0 - weight)


# 3. Dynamic Registration with Ultralytics parse_model
def register():
    # ------------------------------------------------------------
    # Register custom modules
    # ------------------------------------------------------------

    tasks.ECA = ECA
    modules.ECA = ECA

    tasks.AFF = AFF
    modules.AFF = AFF

    # ------------------------------------------------------------
    # Get Ultralytics parse_model source
    #
    # In Kaggle, parse_model may have __code__.co_filename == "<string>",
    # so inspect.getsource() can fail.
    #
    # We therefore fall back to reading the actual tasks.py file.
    # ------------------------------------------------------------

    try:
        src = inspect.getsource(tasks.parse_model)

    except OSError:
        print("inspect.getsource() unavailable.")
        print("Using Ultralytics tasks.py directly...")

        tasks_file = Path(tasks.__file__).resolve()

        if not tasks_file.exists():
            raise FileNotFoundError(
                f"Ultralytics tasks.py not found: {tasks_file}"
            )

        full_source = tasks_file.read_text(
            encoding="utf-8"
        )

        tree = ast.parse(full_source)

        parse_node = None

        for node in tree.body:
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                if node.name == "parse_model":
                    parse_node = node
                    break

        if parse_node is None:
            raise RuntimeError(
                "Could not find parse_model() inside Ultralytics tasks.py"
            )

        src = ast.get_source_segment(
            full_source,
            parse_node
        )

        if not src:
            raise RuntimeError(
                "Could not extract parse_model() source."
            )

        print(
            "Loaded parse_model from:",
            tasks_file
        )

    # ------------------------------------------------------------
    # Patch AFF handling
    # ------------------------------------------------------------

    target = (
        "elif m is Concat:\n"
        "            c2 = sum(ch[x] for x in f)"
    )

    replacement = target + """
        elif m is AFF:
            c2 = args[0] if len(args) else ch[f[-1]]
            args = [[ch[x] for x in f], c2]
"""

    # Avoid registering the same patch twice
    if "elif m is AFF:" not in src:

        if target not in src:
            raise RuntimeError(
                "Could not find the expected Concat branch "
                "inside Ultralytics parse_model(). "
                "Ultralytics version may have changed."
            )

        new_src = src.replace(
            target,
            replacement,
            1
        )

        # --------------------------------------------------------
        # Rebuild parse_model using Ultralytics globals
        # --------------------------------------------------------

        globs = tasks.__dict__.copy()

        globs["ECA"] = ECA
        globs["AFF"] = AFF

        exec(
            new_src,
            globs
        )

        tasks.parse_model = globs["parse_model"]

        print(
            "AFF parser patch applied successfully."
        )

    else:
        print(
            "AFF parser patch already present."
        )
register()


# 4. Ablations Dictionary
ABLATIONS = {
    "A_base":        (False, False, False),
    "B_p2":          (True,  False, False),
    "C_eca":         (False, True,  False),
    "D_p2_eca":      (True,  True,  False),
    "E_EAF_YOLO11n": (True,  True,  True),
}


# 5. Config Generator
def write_cfg(cfg_dir, tag, nc=7):

    p2, eca, aff = ABLATIONS[tag]

    cfg_path = Path(cfg_dir) / f"{tag}.yaml"

    fuse_mod = "AFF" if aff else "Concat"

    backbone = [
        [-1, 1, "Conv", [64, 3, 2]],
        [-1, 1, "Conv", [128, 3, 2]],
        [-1, 2, "C3k2", [256, False, 0.25]],
        [-1, 1, "Conv", [256, 3, 2]],
        [-1, 2, "C3k2", [512, False, 0.25]],
        [-1, 1, "Conv", [512, 3, 2]],
        [-1, 2, "C3k2", [512, True]],
        [-1, 1, "Conv", [1024, 3, 2]],
        [-1, 2, "C3k2", [1024, True]],
        [-1, 1, "SPPF", [1024, 5]],
        [-1, 2, "C2PSA", [1024]],
    ]

    if not p2:

        head = [
            [-1, 1, "nn.Upsample", [None, 2, "nearest"]],
            [[-1, 6], 1, fuse_mod, [128] if aff else [1]],
            [-1, 2, "C3k2", [512, False]],

            [-1, 1, "nn.Upsample", [None, 2, "nearest"]],
            [[-1, 4], 1, fuse_mod, [64] if aff else [1]],
            [-1, 2, "C3k2", [256, False]],

            [-1, 1, "Conv", [256, 3, 2]],
            [[-1, 13], 1, fuse_mod, [128] if aff else [1]],
            [-1, 2, "C3k2", [512, False]],

            [-1, 1, "Conv", [512, 3, 2]],
            [[-1, 10], 1, fuse_mod, [256] if aff else [1]],
            [-1, 2, "C3k2", [1024, True]],
        ]

        det_ins = [16, 19, 22]

        if eca:

            head.append([16, 1, "ECA", [3]])
            head.append([19, 1, "ECA", [3]])
            head.append([22, 1, "ECA", [3]])

            det_ins = [23, 24, 25]

        head.append(
            [det_ins, 1, "Detect", [nc]]
        )

    else:

        head = [
            [-1, 1, "nn.Upsample", [None, 2, "nearest"]],
            [[-1, 6], 1, fuse_mod, [128] if aff else [1]],
            [-1, 2, "C3k2", [512, False]],

            [-1, 1, "nn.Upsample", [None, 2, "nearest"]],
            [[-1, 4], 1, fuse_mod, [64] if aff else [1]],
            [-1, 2, "C3k2", [256, False]],

            [-1, 1, "nn.Upsample", [None, 2, "nearest"]],
            [[-1, 2], 1, fuse_mod, [32] if aff else [1]],
            [-1, 2, "C3k2", [128, False]],

            [-1, 1, "Conv", [128, 3, 2]],
            [[-1, 16], 1, fuse_mod, [64] if aff else [1]],
            [-1, 2, "C3k2", [256, False]],

            [-1, 1, "Conv", [256, 3, 2]],
            [[-1, 13], 1, fuse_mod, [128] if aff else [1]],
            [-1, 2, "C3k2", [512, False]],

            [-1, 1, "Conv", [512, 3, 2]],
            [[-1, 10], 1, fuse_mod, [256] if aff else [1]],
            [-1, 2, "C3k2", [1024, True]],
        ]

        det_ins = [19, 22, 25, 28]

        if eca:

            head.append([19, 1, "ECA", [3]])
            head.append([22, 1, "ECA", [3]])
            head.append([25, 1, "ECA", [3]])
            head.append([28, 1, "ECA", [3]])

            det_ins = [29, 30, 31, 32]

        head.append(
            [det_ins, 1, "Detect", [nc]]
        )

    cfg_dict = {
        "nc": nc,
        "scales": {
            "n": [0.50, 0.25, 1024]
        },
        "backbone": backbone,
        "head": head
    }

    with open(cfg_path, "w") as f:
        yaml.safe_dump(cfg_dict, f)

    return cfg_path
'''


module_path = CODE_DIR / "eaf_modules.py"

with open(module_path, "w", encoding="utf-8") as f:
    f.write(eaf_code)

print("EAF module recreated successfully.")
print("Path:", module_path)
print("Size:", module_path.stat().st_size, "bytes")

EAF module recreated successfully.
Path: /kaggle/working/E_EAF_YOLO11n/code/eaf_modules.py
Size: 9703 bytes

In [26]:
# ------------------------------------------------------------
# Find eaf_modules.py
# ------------------------------------------------------------

module_candidates = list(WORK_ROOT.rglob("eaf_modules.py"))

if not module_candidates:
    raise FileNotFoundError(
        f"eaf_modules.py was not found in {WORK_ROOT}"
    )

EAF_SOURCE = module_candidates[0]

print("EAF module found:")
print(EAF_SOURCE)

EAF module found:
/kaggle/working/E_EAF_YOLO11n/code/eaf_modules.py

In [27]:
# ============================================================
# CELL 2 — FIND DATASET AND EAF MODULE
# ============================================================

TAG = "E_EAF_YOLO11n"
SEED = 42

# Keep 150 epochs for final training
EPOCHS = 150

INPUT_ROOT = Path("/kaggle/input")
WORK_ROOT = Path("/kaggle/working") / TAG

RUNS_DIR = WORK_ROOT / "runs"
CFG_DIR = WORK_ROOT / "configs"
CODE_DIR = WORK_ROOT / "code"
RES_DIR = WORK_ROOT / "results"

for p in (RUNS_DIR, CFG_DIR, CODE_DIR, RES_DIR):
    p.mkdir(parents=True, exist_ok=True)

print("Searching Kaggle input...")
print(INPUT_ROOT)

# ------------------------------------------------------------
# Find eaf_modules.py
# ------------------------------------------------------------


module_candidates = list(WORK_ROOT.rglob("eaf_modules.py"))

if not module_candidates:
    raise FileNotFoundError(
        """
eaf_modules.py was not found.

Attach the Kaggle Dataset containing eaf_modules.py
to this notebook.
"""
    )

EAF_SOURCE = module_candidates[0]



print("EAF module found:")
print(EAF_SOURCE)

# ------------------------------------------------------------
# Find data.yaml
# ------------------------------------------------------------

yaml_candidates = list(INPUT_ROOT.rglob("data.yaml"))


DATA_SOURCE = None

for candidate in yaml_candidates:

    parent = candidate.parent

    has_train = (parent / "train").is_dir()

    has_valid = (
        (parent / "valid").is_dir()
        or
        (parent / "val").is_dir()
    )

    has_test = (parent / "test").is_dir()

    if has_train and has_valid and has_test:
        DATA_SOURCE = candidate
        break

if DATA_SOURCE is None:
    raise FileNotFoundError(
        """
Could not find data.yaml with:

train/
valid/ or val/
test/
"""
    )

print("\nDataset YAML:")
print(DATA_SOURCE)

Searching Kaggle input...
/kaggle/input
EAF module found:
/kaggle/working/E_EAF_YOLO11n/code/eaf_modules.py

Dataset YAML:
/kaggle/input/datasets/muhammadharisabid/fabricdefectntu/data.yaml

In [35]:
# ============================================================
# CELL 3 — RESTORE EAF MODULE
# ============================================================

from pathlib import Path

CODE_DIR = Path("/kaggle/working/E_EAF_YOLO11n/code")
CODE_DIR.mkdir(parents=True, exist_ok=True)

eaf_code = r'''
import ast
import inspect
from pathlib import Path

import torch
import torch.nn as nn
import yaml

import ultralytics.nn.tasks as tasks
import ultralytics.nn.modules as modules


# ============================================================
# 1. Efficient Channel Attention
# ============================================================

class ECA(nn.Module):

    def __init__(self, c1=None, c2=None, k=3):

        super().__init__()

        kernel = 3

        if isinstance(c1, int) and c1 in (3, 5, 7):
            kernel = c1

        elif isinstance(k, int) and k in (3, 5, 7):
            kernel = k

        self.avg_pool = nn.AdaptiveAvgPool2d(1)

        self.conv = nn.Conv1d(
            1,
            1,
            kernel_size=kernel,
            padding=(kernel - 1) // 2,
            bias=False
        )

        self.sigmoid = nn.Sigmoid()


    def forward(self, x):

        y = self.avg_pool(x)

        y = self.conv(
            y.squeeze(-1).transpose(-1, -2)
        ).transpose(-1, -2).unsqueeze(-1)

        return x * self.sigmoid(y)


# ============================================================
# 2. Attentional Feature Fusion
# ============================================================

class AFF(nn.Module):

    def __init__(self, in_channels, out_channels=None):

        super().__init__()

        if isinstance(in_channels, int) and out_channels is None:

            out_channels = in_channels
            in_channels = [in_channels, in_channels]

        elif (
            isinstance(in_channels, int)
            and isinstance(out_channels, int)
        ):

            in_channels = [in_channels, out_channels]

        self.out_channels = out_channels

        self.conv_adapters = nn.ModuleList([

            nn.Conv2d(
                c,
                out_channels,
                1,
                bias=False
            )
            if c != out_channels
            else nn.Identity()

            for c in in_channels

        ])

        mid = max(out_channels // 4, 16)

        self.conv1 = nn.Conv2d(
            out_channels,
            mid,
            1,
            bias=False
        )

        self.bn1 = nn.BatchNorm2d(mid)

        self.relu = nn.ReLU(inplace=True)

        self.conv2 = nn.Conv2d(
            mid,
            out_channels,
            1,
            bias=False
        )

        self.bn2 = nn.BatchNorm2d(out_channels)

        self.global_pool = nn.AdaptiveAvgPool2d(1)

        self.sigmoid = nn.Sigmoid()


    def forward(self, xs):

        if not isinstance(xs, (list, tuple)):
            xs = [xs]

        x0 = self.conv_adapters[0](xs[0])

        x1 = (
            self.conv_adapters[1](xs[1])
            if len(xs) > 1
            else x0
        )

        x_sum = x0 + x1

        loc = self.bn2(
            self.conv2(
                self.relu(
                    self.bn1(
                        self.conv1(x_sum)
                    )
                )
            )
        )

        glo = self.bn2(
            self.conv2(
                self.relu(
                    self.bn1(
                        self.conv1(
                            self.global_pool(x_sum)
                        )
                    )
                )
            )
        )

        weight = self.sigmoid(loc + glo)

        return (
            x0 * weight
            + x1 * (1.0 - weight)
        )


# ============================================================
# 3. Register EAF modules
# ============================================================

def register():

    # --------------------------------------------------------
    # Register custom modules
    # --------------------------------------------------------

    tasks.ECA = ECA
    modules.ECA = ECA

    tasks.AFF = AFF
    modules.AFF = AFF

    # --------------------------------------------------------
    # Get parse_model source
    # --------------------------------------------------------

    try:

        src = inspect.getsource(
            tasks.parse_model
        )

        print(
            "parse_model source obtained with inspect."
        )

    except OSError:

        print(
            "inspect.getsource() unavailable."
        )

        print(
            "Reading Ultralytics tasks.py directly..."
        )

        tasks_file = Path(
            tasks.__file__
        ).resolve()

        print(
            "Ultralytics tasks.py:",
            tasks_file
        )

        if not tasks_file.exists():

            raise FileNotFoundError(
                f"Could not find tasks.py: {tasks_file}"
            )

        full_source = tasks_file.read_text(
            encoding="utf-8"
        )

        tree = ast.parse(
            full_source
        )

        parse_node = None

        for node in tree.body:

            if isinstance(
                node,
                (ast.FunctionDef, ast.AsyncFunctionDef)
            ):

                if node.name == "parse_model":

                    parse_node = node
                    break

        if parse_node is None:

            raise RuntimeError(
                "Could not find parse_model() in tasks.py"
            )

        src = ast.get_source_segment(
            full_source,
            parse_node
        )

        if not src:

            raise RuntimeError(
                "Could not extract parse_model() source."
            )

        print(
            "parse_model source extracted successfully."
        )

    # --------------------------------------------------------
    # Add AFF handling
    # --------------------------------------------------------

    target = (
        "elif m is Concat:\n"
        "            c2 = sum(ch[x] for x in f)"
    )

    replacement = target + """
        elif m is AFF:
            c2 = args[0] if len(args) else ch[f[-1]]
            args = [[ch[x] for x in f], c2]
"""

    if "elif m is AFF:" not in src:

        if target not in src:

            raise RuntimeError(
                "Expected Concat branch was not found "
                "inside Ultralytics parse_model()."
            )

        new_src = src.replace(
            target,
            replacement,
            1
        )

        globs = tasks.__dict__.copy()

        globs["ECA"] = ECA
        globs["AFF"] = AFF

        exec(
            new_src,
            globs
        )

        tasks.parse_model = globs[
            "parse_model"
        ]

        print(
            "AFF parser patch applied successfully."
        )

    else:

        print(
            "AFF parser patch already present."
        )


# IMPORTANT:
# Do NOT call register() here.
#
# Cell 6 will call it explicitly.
# ============================================================


# ============================================================
# 4. Ablations
# ============================================================

ABLATIONS = {

    "A_base":
        (False, False, False),

    "B_p2":
        (True, False, False),

    "C_eca":
        (False, True, False),

    "D_p2_eca":
        (True, True, False),

    "E_EAF_YOLO11n":
        (True, True, True),

}


# ============================================================
# 5. Configuration Generator
# ============================================================

def write_cfg(
    cfg_dir,
    tag,
    nc=7
):

    p2, eca, aff = ABLATIONS[tag]

    cfg_path = (
        Path(cfg_dir)
        / f"{tag}.yaml"
    )

    fuse_mod = (
        "AFF"
        if aff
        else "Concat"
    )

    backbone = [

        [-1, 1, "Conv", [64, 3, 2]],

        [-1, 1, "Conv", [128, 3, 2]],

        [-1, 2, "C3k2",
         [256, False, 0.25]],

        [-1, 1, "Conv",
         [256, 3, 2]],

        [-1, 2, "C3k2",
         [512, False, 0.25]],

        [-1, 1, "Conv",
         [512, 3, 2]],

        [-1, 2, "C3k2",
         [512, True]],

        [-1, 1, "Conv",
         [1024, 3, 2]],

        [-1, 2, "C3k2",
         [1024, True]],

        [-1, 1, "SPPF",
         [1024, 5]],

        [-1, 2, "C2PSA",
         [1024]],

    ]


    if not p2:

        head = [

            [-1, 1, "nn.Upsample",
             [None, 2, "nearest"]],

            [[-1, 6], 1,
             fuse_mod,
             [128] if aff else [1]],

            [-1, 2, "C3k2",
             [512, False]],

            [-1, 1, "nn.Upsample",
             [None, 2, "nearest"]],

            [[-1, 4], 1,
             fuse_mod,
             [64] if aff else [1]],

            [-1, 2, "C3k2",
             [256, False]],

            [-1, 1, "Conv",
             [256, 3, 2]],

            [[-1, 13], 1,
             fuse_mod,
             [128] if aff else [1]],

            [-1, 2, "C3k2",
             [512, False]],

            [-1, 1, "Conv",
             [512, 3, 2]],

            [[-1, 10], 1,
             fuse_mod,
             [256] if aff else [1]],

            [-1, 2, "C3k2",
             [1024, True]],

        ]

        det_ins = [16, 19, 22]

        if eca:

            head.append(
                [16, 1, "ECA", [3]]
            )

            head.append(
                [19, 1, "ECA", [3]]
            )

            head.append(
                [22, 1, "ECA", [3]]
            )

            det_ins = [23, 24, 25]

        head.append(
            [det_ins, 1, "Detect", [nc]]
        )

    else:

        head = [

            [-1, 1, "nn.Upsample",
             [None, 2, "nearest"]],

            [[-1, 6], 1,
             fuse_mod,
             [128] if aff else [1]],

            [-1, 2, "C3k2",
             [512, False]],

            [-1, 1, "nn.Upsample",
             [None, 2, "nearest"]],

            [[-1, 4], 1,
             fuse_mod,
             [64] if aff else [1]],

            [-1, 2, "C3k2",
             [256, False]],

            [-1, 1, "nn.Upsample",
             [None, 2, "nearest"]],

            [[-1, 2], 1,
             fuse_mod,
             [32] if aff else [1]],

            [-1, 2, "C3k2",
             [128, False]],

            [-1, 1, "Conv",
             [128, 3, 2]],

            [[-1, 16], 1,
             fuse_mod,
             [64] if aff else [1]],

            [-1, 2, "C3k2",
             [256, False]],

            [-1, 1, "Conv",
             [256, 3, 2]],

            [[-1, 13], 1,
             fuse_mod,
             [128] if aff else [1]],

            [-1, 2, "C3k2",
             [512, False]],

            [-1, 1, "Conv",
             [512, 3, 2]],

            [[-1, 10], 1,
             fuse_mod,
             [256] if aff else [1]],

            [-1, 2, "C3k2",
             [1024, True]],

        ]

        det_ins = [
            19, 22, 25, 28
        ]

        if eca:

            head.append(
                [19, 1, "ECA", [3]]
            )

            head.append(
                [22, 1, "ECA", [3]]
            )

            head.append(
                [25, 1, "ECA", [3]]
            )

            head.append(
                [28, 1, "ECA", [3]]
            )

            det_ins = [
                29, 30, 31, 32
            ]

        head.append(
            [det_ins, 1, "Detect", [nc]]
        )


    cfg_dict = {

        "nc": nc,

        "scales": {
            "n": [0.50, 0.25, 1024]
        },

        "backbone": backbone,

        "head": head

    }


    with open(
        cfg_path,
        "w"
    ) as f:

        yaml.safe_dump(
            cfg_dict,
            f
        )

    return cfg_path
'''

module_path = CODE_DIR / "eaf_modules.py"

with open(
    module_path,
    "w",
    encoding="utf-8"
) as f:
    f.write(eaf_code)

print("EAF module recreated successfully.")
print("Path:", module_path)
print("Size:", module_path.stat().st_size, "bytes")

EAF module recreated successfully.
Path: /kaggle/working/E_EAF_YOLO11n/code/eaf_modules.py
Size: 11484 bytes

In [36]:
# ============================================================
# RELOAD EAF MODULE
# ============================================================

import sys
import importlib

if str(CODE_DIR) not in sys.path:
    sys.path.insert(0, str(CODE_DIR))

if "eaf_modules" in sys.modules:
    del sys.modules["eaf_modules"]

import eaf_modules as eaf

print("Loaded:")
print(eaf.__file__)

Loaded:
/kaggle/working/E_EAF_YOLO11n/code/eaf_modules.py

In [29]:
# ============================================================
# CELL 4 — CREATE KAGGLE DATA.YAML
# ============================================================

with open(
    DATA_SOURCE,
    "r",
    encoding="utf-8"
) as f:

    src = yaml.safe_load(f)


names = src["names"]
NC = len(names)

DATA_YAML = DATASET_DIR / "data.yaml"

yaml.safe_dump(
    {
        "path": str(DATASET_DIR),

        "train": f"{train_name}/images",

        "val": f"{val_name}/images",

        "test": f"{test_name}/images",

        "nc": NC,

        "names": names,
    },

    open(
        DATA_YAML,
        "w",
        encoding="utf-8"
    ),

    sort_keys=False
)


print("Number of classes:", NC)
print("Class names:")
print(names)

print("\nDATA_YAML:")
print(DATA_YAML)

Number of classes: 7
Class names:
['baekra', 'color issues', 'contamination', 'cut', 'gray stitch', 'selvet', 'stain']

DATA_YAML:
/kaggle/working/E_EAF_YOLO11n/dataset/data.yaml

In [30]:
# ============================================================
# CELL 5 — DATASET SANITY CHECK
# ============================================================

IMAGE_EXTS = {
    ".jpg",
    ".jpeg",
    ".png",
    ".bmp",
    ".webp"
}


def count_images(folder):

    return sum(
        1
        for p in folder.rglob("*")
        if p.suffix.lower() in IMAGE_EXTS
    )


def count_labels(folder):

    label_dir = folder / "labels"

    if not label_dir.exists():
        return 0

    return len(
        list(label_dir.glob("*.txt"))
    )


train_images = count_images(
    DATASET_DIR / train_name / "images"
)

val_images = count_images(
    DATASET_DIR / val_name / "images"
)

test_images = count_images(
    DATASET_DIR / test_name / "images"
)

train_labels = count_labels(
    DATASET_DIR / train_name
)

val_labels = count_labels(
    DATASET_DIR / val_name
)

test_labels = count_labels(
    DATASET_DIR / test_name
)


print("================================")
print("DATASET SUMMARY")
print("================================")

print("Train images :", train_images)
print("Train labels :", train_labels)

print("Val images   :", val_images)
print("Val labels   :", val_labels)

print("Test images  :", test_images)
print("Test labels  :", test_labels)

print("Classes      :", NC)
print("================================")

================================
DATASET SUMMARY
================================
Train images : 1950
Train labels : 1950
Val images   : 562
Val labels   : 562
Test images  : 280
Test labels  : 280
Classes      : 7
================================

In [31]:
from pathlib import Path

CODE_DIR = Path("/kaggle/working/E_EAF_YOLO11n/code")

print("CODE_DIR:", CODE_DIR)
print("\nFiles inside code folder:")

for p in CODE_DIR.iterdir():
    print(" -", p.name)

EAF_FILE = CODE_DIR / "eaf_modules.py"

print("\nEAF module exists:", EAF_FILE.exists())

if EAF_FILE.exists():
    print("EAF module:", EAF_FILE)
    print("Size:", EAF_FILE.stat().st_size, "bytes")

CODE_DIR: /kaggle/working/E_EAF_YOLO11n/code

Files inside code folder:
 - eaf_modules.py
 - __pycache__

EAF module exists: True
EAF module: /kaggle/working/E_EAF_YOLO11n/code/eaf_modules.py
Size: 9703 bytes

In [33]:
# ============================================================
# DIAGNOSTIC — CHECK ULTRALYTICS parse_model
# ============================================================

import ultralytics
import inspect
import ultralytics.nn.tasks as tasks

print("Ultralytics version:", ultralytics.__version__)
print("parse_model:", tasks.parse_model)

try:
    print("parse_model file:", inspect.getfile(tasks.parse_model))
except Exception as e:
    print("Could not get file:", repr(e))

print("parse_model filename:", tasks.parse_model.__code__.co_filename)

try:
    src = inspect.getsource(tasks.parse_model)
    print("\nSource available: YES")
    print("Source length:", len(src))
except Exception as e:
    print("\nSource available: NO")
    print("Error:", repr(e))

Ultralytics version: 8.4.174
parse_model: <function parse_model at 0x7d64a8dad300>
parse_model file: <string>
parse_model filename: <string>

Source available: NO
Error: OSError('could not get source code')

In [37]:
# ============================================================
# CELL 6 — LOAD EAF MODULE
# ============================================================

sys.path.insert(
    0,
    str(CODE_DIR)
)

import eaf_modules as eaf

# IMPORTANT:
# Must be executed in every fresh Kaggle session.
eaf.register()

print("EAF module registered successfully.")

CFG = eaf.write_cfg(
    CFG_DIR,
    TAG,
    NC
)

print("EAF configuration:")
print(CFG)

inspect.getsource() unavailable.
Reading Ultralytics tasks.py directly...
Ultralytics tasks.py: /usr/local/lib/python3.13/dist-packages/ultralytics/nn/tasks.py
parse_model source extracted successfully.
AFF parser patch applied successfully.
EAF module registered successfully.
EAF configuration:
/kaggle/working/E_EAF_YOLO11n/configs/E_EAF_YOLO11n.yaml

In [38]:
# ============================================================
# CELL 7 — EAF SANITY CHECK
# ============================================================

model_test = YOLO(
    str(CFG)
).model

model_test.train()

x = torch.randn(
    2,
    3,
    320,
    320
)

out = model_test(x)


def tensors(obj):

    if torch.is_tensor(obj):

        yield obj

    elif isinstance(obj, dict):

        for value in obj.values():
            yield from tensors(value)

    elif isinstance(obj, (list, tuple)):

        for value in obj:
            yield from tensors(value)


loss_proxy = sum(
    t.float().pow(2).mean()
    for t in tensors(out)
)

loss_proxy.backward()


dead = [
    name
    for name, parameter
    in model_test.named_parameters()
    if parameter.requires_grad
    and parameter.grad is None
]


assert not dead, (
    f"Parameters without gradients: {dead[:10]}"
)


params_m = (
    sum(
        p.numel()
        for p in model_test.parameters()
    )
    / 1e6
)


print("================================")
print("EAF SANITY CHECK: PASS")
print("================================")
print(
    "Parameters:",
    round(params_m, 3),
    "M"
)
print("================================")


del model_test
del out
del x

torch.cuda.empty_cache()

WARNING ⚠️ no model scale passed. Assuming scale='n'.
================================
EAF SANITY CHECK: PASS
================================
Parameters: 2.729 M
================================

In [39]:
# ============================================================
# CELL 8 — IMPROVED TRAINING CONFIGURATION
# ============================================================

TRAIN_CFG = dict(

    data=str(DATA_YAML),

    # --------------------------------------------------------
    # IMAGE / TRAINING
    # --------------------------------------------------------

    imgsz=640,

    epochs=EPOCHS,

    batch=16,

    device=0,

    workers=2,

    # --------------------------------------------------------
    # OPTIMIZER
    # --------------------------------------------------------

    optimizer="AdamW",

    # Lower LR = more stable fine tuning
    lr0=5e-4,

    lrf=0.01,

    weight_decay=5e-4,

    cos_lr=True,

    warmup_epochs=3.0,

    # --------------------------------------------------------
    # COLOR AUGMENTATION
    # --------------------------------------------------------

    hsv_h=0.01,

    hsv_s=0.35,

    hsv_v=0.25,

    # --------------------------------------------------------
    # GEOMETRIC AUGMENTATION
    # --------------------------------------------------------

    degrees=2.0,

    translate=0.05,

    scale=0.20,

    shear=1.0,

    perspective=0.0,

    # --------------------------------------------------------
    # FLIPPING
    # --------------------------------------------------------

    fliplr=0.5,

    # Important for fabric:
    # don't vertically flip the fabric defects
    flipud=0.0,

    # --------------------------------------------------------
    # MOSAIC
    # --------------------------------------------------------

    mosaic=0.70,

    close_mosaic=20,

    # Don't combine unrelated defect images
    mixup=0.0,

    # --------------------------------------------------------
    # REGULARIZATION
    # --------------------------------------------------------

    label_smoothing=0.02,

    # --------------------------------------------------------
    # PERFORMANCE
    # --------------------------------------------------------

    amp=True,

    cache=False,

    # --------------------------------------------------------
    # REPRODUCIBILITY
    # --------------------------------------------------------

    seed=SEED,

    deterministic=True,

    # --------------------------------------------------------
    # OUTPUT
    # --------------------------------------------------------

    project=str(RUNS_DIR),

    name=TAG,

    exist_ok=True,

    plots=True,

    save=True,

    # Save every 10 epochs
    save_period=10,

    # Early stopping
    patience=30,
)


print("Training configuration:\n")

for key, value in TRAIN_CFG.items():

    print(
        f"{key:20} : {value}"
    )

Training configuration:

data                 : /kaggle/working/E_EAF_YOLO11n/dataset/data.yaml
imgsz                : 640
epochs               : 150
batch                : 16
device               : 0
workers              : 2
optimizer            : AdamW
lr0                  : 0.0005
lrf                  : 0.01
weight_decay         : 0.0005
cos_lr               : True
warmup_epochs        : 3.0
hsv_h                : 0.01
hsv_s                : 0.35
hsv_v                : 0.25
degrees              : 2.0
translate            : 0.05
scale                : 0.2
shear                : 1.0
perspective          : 0.0
fliplr               : 0.5
flipud               : 0.0
mosaic               : 0.7
close_mosaic         : 20
mixup                : 0.0
label_smoothing      : 0.02
amp                  : True
cache                : False
seed                 : 42
deterministic        : True
project              : /kaggle/working/E_EAF_YOLO11n/runs
name                 : E_EAF_YOLO11n
exist_ok             : True
plots                : True
save                 : True
save_period          : 10
patience             : 30

In [40]:
# ============================================================
# CELL 9 — TRAIN / AUTO RESUME
# ============================================================

BEST = (
    RUNS_DIR
    / TAG
    / "weights"
    / "best.pt"
)

LAST = (
    RUNS_DIR
    / TAG
    / "weights"
    / "last.pt"
)

DONE = (
    RUNS_DIR
    / TAG
    / "DONE"
)


# ------------------------------------------------------------
# CASE 1 — Already completed
# ------------------------------------------------------------

if DONE.exists():

    print("================================")
    print("TRAINING ALREADY COMPLETED")
    print("================================")

    print("Best:")
    print(BEST)


# ------------------------------------------------------------
# CASE 2 — Previous run exists
# ------------------------------------------------------------

elif LAST.exists():

    print("================================")
    print("RESUMING TRAINING")
    print("================================")

    print("Checkpoint:")
    print(LAST)

    model = YOLO(
        str(LAST)
    )

    model.train(
        resume=True
    )

    DONE.touch()

    print("Training resumed successfully.")


# ------------------------------------------------------------
# CASE 3 — Start new training
# ------------------------------------------------------------

else:

    print("================================")
    print("STARTING NEW TRAINING")
    print("================================")

    model = YOLO(
        str(CFG)
    )

    # Transfer pretrained YOLO11n weights
    model.load(
        "yolo11n.pt"
    )

    print("Pretrained YOLO11n weights loaded.")

    model.train(
        **TRAIN_CFG
    )

    DONE.touch()

    print("Training completed.")


# ------------------------------------------------------------
# Show checkpoints
# ------------------------------------------------------------

print("\nCHECKPOINTS:")

for p in sorted(
    (
        RUNS_DIR
        / TAG
        / "weights"
    ).glob("*.pt")
):

    print(
        p.name,
        "->",
        round(
            p.stat().st_size / 2**20,
            2
        ),
        "MB"
    )

================================
STARTING NEW TRAINING
================================
WARNING ⚠️ no model scale passed. Assuming scale='n'.
Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/yolo11n.pt to 'yolo11n.pt': 100% ━━━━━━━━━━━━ 5.4MB 55.1MB/s 0.1s
Transferred 295/677 items from pretrained weights
Pretrained YOLO11n weights loaded.
WARNING ⚠️ 'label_smoothing' is deprecated and will be removed in the future.
Ultralytics 8.4.174 🚀 Python-3.13.15 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, channels_last=None, classes=None, close_mosaic=20, cls=0.5, cls_pw=0.0, cls_remap=True, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=True, cutmix=0.0, data=/kaggle/working/E_EAF_YOLO11n/dataset/data.yaml, degrees=2.0, deterministic=True, device=0, dfl=1.5, dgrad=0.5, dis=6.0, distill_model=None, dlam=1.0, dlog=1.0, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=150, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, hsv_h=0.01, hsv_s=0.35, hsv_v=0.25, imgsz=640, iou=0.7, kobj=1.0, line_width=None, lr0=0.0005, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=/kaggle/working/E_EAF_YOLO11n/configs/E_EAF_YOLO11n.yaml, momentum=0.937, mosaic=0.7, multi_scale=0.0, name=E_EAF_YOLO11n, nbs=64, nms=None, opset=None, optimize=False, optimizer=AdamW, overlap_mask=True, patience=30, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=/kaggle/working/E_EAF_YOLO11n/runs, quantize=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/kaggle/working/E_EAF_YOLO11n/runs/E_EAF_YOLO11n, save_frames=False, save_json=False, save_period=10, save_txt=False, scale=0.2, seed=42, shear=1.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=tracktrack.yaml, translate=0.05, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=2, workspace=None
Downloading https://ultralytics.com/assets/Arial.ttf to '/root/.config/Ultralytics/Arial.ttf': 100% ━━━━━━━━━━━━ 755.1KB 27.4MB/s 0.0s
WARNING ⚠️ no model scale passed. Assuming scale='n'.

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      6640  ultralytics.nn.modules.block.C3k2            [32, 64, 1, False, 0.25]
  3                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
  4                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  5                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  6                  -1  1     87040  ultralytics.nn.modules.block.C3k2            [128, 128, 1, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1    249728  ultralytics.nn.modules.block.C2PSA           [256, 256, 1]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1     41280  eaf_modules.AFF                              [[256, 128], 128]
 13                  -1  1     78528  ultralytics.nn.modules.block.C3k2            [128, 128, 1, False]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1     18592  eaf_modules.AFF                              [[128, 128], 64]
 16                  -1  1     19808  ultralytics.nn.modules.block.C3k2            [64, 64, 1, False]
 17                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 18             [-1, 2]  1      5216  eaf_modules.AFF                              [[64, 64], 32]
 19                  -1  1      5040  ultralytics.nn.modules.block.C3k2            [32, 32, 1, False]
 20                  -1  1      9280  ultralytics.nn.modules.conv.Conv             [32, 32, 3, 2]
 21            [-1, 16]  1      4256  eaf_modules.AFF                              [[32, 64], 64]
 22                  -1  1     19808  ultralytics.nn.modules.block.C3k2            [64, 64, 1, False]
 23                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 24            [-1, 13]  1     16704  eaf_modules.AFF                              [[64, 128], 128]
 25                  -1  1     78528  ultralytics.nn.modules.block.C3k2            [128, 128, 1, False]
 26                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 27            [-1, 10]  1     66176  eaf_modules.AFF                              [[128, 256], 256]
 28                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
 29                  19  1         3  eaf_modules.ECA                              [3]
 30                  22  1         3  eaf_modules.ECA                              [3]
 31                  25  1         3  eaf_modules.ECA                              [3]
 32                  28  1         3  eaf_modules.ECA                              [3]
 33    [29, 30, 31, 32]  1    469196  ultralytics.nn.modules.head.Detect           [7, 16, None, [32, 64, 128, 256]]
E_EAF_YOLO11n summary: 276 layers, 2,728,712 parameters, 2,728,696 gradients, 10.8 GFLOPs

Transferred 677/677 items from pretrained weights
Freezing layer 'model.33.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: downloading yolo26n.pt for AMP checks (one-time, not used for training)...
Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/yolo26n.pt to 'weights/yolo26n.pt': 100% ━━━━━━━━━━━━ 5.3MB 100.2MB/s 0.1s
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 1412.0±438.3 MB/s, size: 167.6 KB)
train: Scanning /kaggle/working/E_EAF_YOLO11n/dataset/train/labels... 1950 images, 161 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1950/1950 1.3Kit/s 1.5s0.1s
train: New cache created: /kaggle/working/E_EAF_YOLO11n/dataset/train/labels.cache
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 2641.5±1059.7 MB/s, size: 128.1 KB)
val: Scanning /kaggle/working/E_EAF_YOLO11n/dataset/valid/labels... 562 images, 38 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 562/562 1.3Kit/s 0.4s0.0ss
val: New cache created: /kaggle/working/E_EAF_YOLO11n/dataset/valid/labels.cache
optimizer: AdamW(lr=0.0005, momentum=0.937) with parameter groups 108 weight(decay=0.0), 129 weight(decay=0.0005), 116 bias(decay=0.0)
Plotting labels to /kaggle/working/E_EAF_YOLO11n/runs/E_EAF_YOLO11n/labels.jpg...
Using 1950 train, 562 val images for fraction=1.0 at imgsz=640
Using 2 dataloader workers
Logging results to /kaggle/working/E_EAF_YOLO11n/runs/E_EAF_YOLO11n
Starting training for 150 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      1/150      4.03G       3.27      4.926      3.512         25        640: 100% ━━━━━━━━━━━━ 122/122 2.2it/s 54.6s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 18/18 2.1s/it 37.0s0.4s
                   all        562        786    0.00356     0.0692      0.002    0.00042

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

/usr/local/lib/python3.13/dist-packages/ray/train/_internal/session.py:683: UserWarning: `get_trial_id` is meant to only be called inside a function that is executed by a Tuner or Trainer. Returning `None`.
  warnings.warn(

      2/150      4.99G      3.135      4.219      3.271         45        640: 100% ━━━━━━━━━━━━ 122/122 5.2it/s 23.5s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 18/18 4.9it/s 3.6s0.2s
                   all        562        786      0.319     0.0456     0.0312    0.00762

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      3/150         5G      2.861      3.732      3.093         33        640: 100% ━━━━━━━━━━━━ 122/122 5.1it/s 23.8s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 18/18 4.6it/s 3.9s0.2s
                   all        562        786      0.239      0.147     0.0727     0.0224

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      4/150         5G      2.597      3.479      2.897         35        640: 100% ━━━━━━━━━━━━ 122/122 5.1it/s 23.9s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 18/18 4.5it/s 4.0s0.2s
                   all        562        786      0.144      0.119     0.0874     0.0279

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      5/150         5G      2.464      3.338      2.763         35        640: 100% ━━━━━━━━━━━━ 122/122 5.0it/s 24.2s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 18/18 4.5it/s 4.0s0.2s
                   all        562        786      0.319      0.215       0.14     0.0492

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      6/150         5G      2.329      3.167      2.647         25        640: 100% ━━━━━━━━━━━━ 122/122 5.0it/s 24.3s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 18/18 4.7it/s 3.8s0.2s
                   all        562        786      0.284       0.23       0.16     0.0497

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      7/150         5G      2.273      2.993      2.578         37        640: 100% ━━━━━━━━━━━━ 122/122 5.0it/s 24.5s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 18/18 4.5it/s 4.0s0.2s
                   all        562        786      0.287      0.264      0.209      0.081

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      8/150         5G      2.207      2.928      2.494         26        640: 100% ━━━━━━━━━━━━ 122/122 4.9it/s 24.9s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 18/18 4.6it/s 3.9s0.2s
                   all        562        786      0.245      0.298      0.217     0.0766

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      9/150         5G      2.153      2.872      2.474         26        640: 100% ━━━━━━━━━━━━ 122/122 4.7it/s 26.0s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 18/18 4.6it/s 3.9s0.2s
                   all        562        786      0.479       0.23      0.226     0.0855

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     10/150         5G      2.125      2.781      2.427         31        640: 100% ━━━━━━━━━━━━ 122/122 4.9it/s 24.8s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 18/18 4.7it/s 3.8s0.2s
                   all        562        786      0.432      0.293       0.25      0.101

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     11/150         5G      2.075      2.701      2.398         26        640: 100% ━━━━━━━━━━━━ 122/122 4.7it/s 25.7s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 18/18 4.5it/s 4.0s0.2s
                   all        562        786      0.336      0.311      0.285      0.119

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     12/150         5G      2.023      2.641      2.349         36        640: 100% ━━━━━━━━━━━━ 122/122 4.6it/s 26.3s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 18/18 4.7it/s 3.8s0.2s
                   all        562        786       0.39      0.321      0.286      0.124

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     13/150         5G      1.986      2.587      2.321         30        640: 100% ━━━━━━━━━━━━ 122/122 4.9it/s 25.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 18/18 4.5it/s 4.0s0.2s
                   all        562        786      0.431      0.348      0.326      0.136

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     14/150         5G      1.961      2.508      2.284         21        640: 100% ━━━━━━━━━━━━ 122/122 4.7it/s 25.8s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 18/18 4.5it/s 4.0s0.2s
                   all        562        786      0.514      0.344      0.323      0.126

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     15/150         5G       1.93      2.457      2.256         35        640: 100% ━━━━━━━━━━━━ 122/122 4.8it/s 25.6s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 18/18 4.6it/s 3.9s0.2s
                   all        562        786      0.402      0.367      0.359      0.157

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     16/150         5G      1.942       2.45      2.246         29        640: 100% ━━━━━━━━━━━━ 122/122 4.8it/s 25.4s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 18/18 4.5it/s 4.0s0.2s
                   all        562        786      0.287      0.406       0.33      0.144

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     17/150         5G      1.906       2.42      2.219         47        640: 100% ━━━━━━━━━━━━ 122/122 4.8it/s 25.7s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 18/18 4.5it/s 4.0s0.2s
                   all        562        786        0.4       0.39      0.344      0.142

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     18/150         5G      1.882      2.326        2.2         26        640: 100% ━━━━━━━━━━━━ 122/122 4.8it/s 25.5s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 18/18 4.6it/s 3.9s0.2s
                   all        562        786       0.53      0.406      0.424      0.194

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     19/150         5G       1.85      2.288      2.182         32        640: 100% ━━━━━━━━━━━━ 122/122 4.8it/s 25.4s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 18/18 4.6it/s 3.9s0.2s
                   all        562        786       0.46      0.384      0.383      0.166

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     20/150         5G      1.848      2.283      2.158         29        640: 100% ━━━━━━━━━━━━ 122/122 4.8it/s 25.6s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 18/18 4.5it/s 4.0s0.2s
                   all        562        786      0.463      0.385      0.394      0.175

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     21/150         5G      1.811      2.214      2.126         35        640: 100% ━━━━━━━━━━━━ 122/122 4.8it/s 25.5s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 18/18 4.6it/s 3.9s0.2s
                   all        562        786      0.577      0.377      0.393      0.182

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     22/150         5G       1.79      2.214      2.109         25        640: 100% ━━━━━━━━━━━━ 122/122 4.8it/s 25.5s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 18/18 4.6it/s 3.9s0.2s
                   all        562        786      0.455      0.422      0.414      0.194

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     23/150         5G      1.778      2.138      2.085         23        640: 100% ━━━━━━━━━━━━ 122/122 4.8it/s 25.5s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 18/18 4.7it/s 3.8s0.2s
                   all        562        786      0.644      0.425      0.468      0.218

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     24/150         5G      1.772      2.151      2.072         35        640: 100% ━━━━━━━━━━━━ 122/122 4.8it/s 25.6s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 18/18 4.7it/s 3.9s0.2s
                   all        562        786      0.501      0.459      0.478      0.231

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     25/150         5G      1.753      2.085      2.087         29        640: 100% ━━━━━━━━━━━━ 122/122 4.8it/s 25.5s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 18/18 4.8it/s 3.8s0.2s
                   all        562        786      0.567      0.483      0.518      0.247

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     26/150         5G      1.736      2.063      2.065         27        640: 100% ━━━━━━━━━━━━ 122/122 4.8it/s 25.5s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 18/18 4.7it/s 3.8s0.2s
                   all        562        786      0.618      0.413      0.488      0.233

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     27/150         5G      1.738      2.031      2.037         50        640: 100% ━━━━━━━━━━━━ 122/122 4.8it/s 25.6s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 18/18 4.6it/s 3.9s0.2s
                   all        562        786      0.537      0.482      0.464      0.226

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     28/150         5G       1.72      2.027      2.025         31        640: 100% ━━━━━━━━━━━━ 122/122 4.8it/s 25.6s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 18/18 4.7it/s 3.8s0.2s
                   all        562        786      0.528      0.483      0.492      0.233

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     29/150         5G      1.705      1.976      2.014         36        640: 100% ━━━━━━━━━━━━ 122/122 4.8it/s 25.6s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 18/18 4.7it/s 3.9s0.2s
                   all        562        786      0.596      0.536      0.562      0.272

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     30/150         5G      1.706      1.991      2.017         30        640: 100% ━━━━━━━━━━━━ 122/122 4.8it/s 25.6s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 18/18 4.8it/s 3.8s0.2s
                   all        562        786      0.558      0.484      0.508      0.246

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     31/150         5G      1.674      1.918      2.003         32        640: 100% ━━━━━━━━━━━━ 122/122 4.8it/s 25.5s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 18/18 4.6it/s 3.9s0.2s
                   all        562        786      0.596       0.52      0.548      0.266

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     32/150         5G      1.681      1.928      1.991         28        640: 100% ━━━━━━━━━━━━ 122/122 4.8it/s 25.6s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 18/18 4.6it/s 3.9s0.2s
                   all        562        786      0.618      0.488      0.535      0.257

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     33/150         5G      1.652      1.867      1.974         25        640: 100% ━━━━━━━━━━━━ 122/122 4.8it/s 25.6s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 18/18 4.6it/s 3.9s0.2s
                   all        562        786      0.559      0.519      0.544      0.263

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     34/150         5G      1.633      1.846      1.942         33        640: 100% ━━━━━━━━━━━━ 122/122 4.8it/s 25.4s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 18/18 4.8it/s 3.8s0.2s
                   all        562        786        0.6      0.513       0.56      0.278

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     35/150         5G      1.617      1.811      1.929         31        640: 100% ━━━━━━━━━━━━ 122/122 4.8it/s 25.4s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 18/18 4.7it/s 3.9s0.2s
                   all        562        786      0.607      0.556      0.557      0.279

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     36/150         5G      1.622      1.795      1.947         23        640: 100% ━━━━━━━━━━━━ 122/122 4.8it/s 25.5s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 18/18 4.7it/s 3.8s0.2s
                   all        562        786      0.677       0.52      0.582      0.288

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     37/150         5G       1.63      1.798      1.945         27        640: 100% ━━━━━━━━━━━━ 122/122 4.8it/s 25.5s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 18/18 4.6it/s 3.9s0.2s
                   all        562        786      0.663       0.54       0.59      0.283

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     38/150         5G      1.593      1.757      1.938         24        640: 100% ━━━━━━━━━━━━ 122/122 4.8it/s 25.5s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 18/18 4.6it/s 3.9s0.2s
                   all        562        786      0.632      0.576       0.62      0.305

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     39/150         5G      1.579      1.714      1.886         36        640: 100% ━━━━━━━━━━━━ 122/122 4.8it/s 25.6s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 18/18 4.5it/s 4.0s0.2s
                   all        562        786      0.645      0.546      0.589      0.294

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     40/150         5G      1.582      1.712      1.913         30        640: 100% ━━━━━━━━━━━━ 122/122 4.8it/s 25.6s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 18/18 4.5it/s 4.0s0.2s
                   all        562        786      0.608      0.558      0.613      0.306

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     41/150         5G      1.587      1.722      1.902         45        640: 100% ━━━━━━━━━━━━ 122/122 4.8it/s 25.6s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 18/18 4.6it/s 3.9s0.2s
                   all        562        786      0.652      0.552      0.586      0.296

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     42/150         5G      1.562      1.669      1.881         35        640: 100% ━━━━━━━━━━━━ 122/122 4.8it/s 25.6s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 18/18 4.6it/s 3.9s0.2s
                   all        562        786      0.687      0.571      0.615      0.323

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     43/150         5G      1.565      1.669      1.886         28        640: 100% ━━━━━━━━━━━━ 122/122 4.8it/s 25.6s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 18/18 4.5it/s 4.0s0.2s
                   all        562        786      0.674      0.584      0.638      0.319

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     44/150         5G      1.557      1.638      1.864         27        640: 100% ━━━━━━━━━━━━ 122/122 4.8it/s 25.6s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 18/18 4.6it/s 3.9s0.2s
                   all        562        786      0.686      0.582      0.632      0.316

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     45/150         5G      1.538      1.642      1.843         29        640: 100% ━━━━━━━━━━━━ 122/122 4.8it/s 25.6s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 18/18 4.6it/s 3.9s0.2s
                   all        562        786      0.628      0.588      0.624      0.319

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     46/150         5G      1.506       1.58      1.828         23        640: 100% ━━━━━━━━━━━━ 122/122 4.8it/s 25.5s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 18/18 4.5it/s 4.0s0.2s
                   all        562        786      0.674      0.621      0.669      0.347

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     47/150         5G      1.487      1.592      1.822         31        640: 100% ━━━━━━━━━━━━ 122/122 4.8it/s 25.6s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 18/18 4.6it/s 3.9s0.2s
                   all        562        786      0.623      0.605      0.641      0.328

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     48/150         5G       1.51      1.596      1.825         35        640: 100% ━━━━━━━━━━━━ 122/122 4.8it/s 25.6s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 18/18 4.5it/s 4.0s0.2s
                   all        562        786       0.66       0.61      0.639      0.309

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     49/150         5G      1.487      1.545      1.812         36        640: 100% ━━━━━━━━━━━━ 122/122 4.7it/s 25.8s0.2s

In [41]:
# ============================================================
# CELL 10 — BEST MODEL CHECK
# ============================================================

if not BEST.exists():

    raise FileNotFoundError(
        f"best.pt not found at:\n{BEST}"
    )


print("================================")
print("BEST MODEL FOUND")
print("================================")
print(BEST)

print(
    "Size:",
    round(
        BEST.stat().st_size / 2**20,
        2
    ),
    "MB"
)

================================
BEST MODEL FOUND
================================
/kaggle/working/E_EAF_YOLO11n/runs/E_EAF_YOLO11n/weights/best.pt
Size: 5.64 MB

In [42]:
# ============================================================
# CELL 11 — VALIDATION + TEST METRICS
# ============================================================

def evaluate(split):

    mdl = YOLO(
        str(BEST)
    )

    result = mdl.val(

        data=str(DATA_YAML),

        split=split,

        imgsz=640,

        batch=16,

        # Required for standard mAP evaluation
        conf=0.001,

        iou=0.7,

        device=0,

        plots=(split == "test"),

        project=str(
            RES_DIR / "evaluation"
        ),

        name=f"{TAG}_{split}",

        exist_ok=True,

        verbose=False,
    )

    b = result.box

    row = {

        "Model": TAG,

        "Split": split,

        "Precision": float(
            b.mp
        ),

        "Recall": float(
            b.mr
        ),

        "mAP50": float(
            b.map50
        ),

        "mAP75": float(
            b.map75
        ),

        "mAP50-95": float(
            b.map
        ),
    }


    indices = list(
        b.ap_class_index
    )


    pc = pd.DataFrame({

        "class": [
            mdl.names[int(i)]
            for i in indices
        ],

        "Precision": b.p,

        "Recall": b.r,

        "F1": b.f1,

        "AP50": b.ap50,

        "AP50-95": b.ap,

    }).round(4)


    return row, pc


print("Evaluating validation set...")

val_row, val_pc = evaluate(
    "val"
)


print("Evaluating test set...")

test_row, test_pc = evaluate(
    "test"
)


print("\n================================")
print("VALIDATION")
print("================================")

display(
    pd.DataFrame([val_row]).round(4)
)


print("\n================================")
print("TEST")
print("================================")

display(
    pd.DataFrame([test_row]).round(4)
)


print("\n================================")
print("PER-CLASS TEST METRICS")
print("================================")

display(
    test_pc
)

Evaluating validation set...
Ultralytics 8.4.174 🚀 Python-3.13.15 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
E_EAF_YOLO11n summary (fused): 180 layers, 2,720,760 parameters, 0 gradients, 10.6 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 3032.5±1433.0 MB/s, size: 171.8 KB)
val: Scanning /kaggle/working/E_EAF_YOLO11n/dataset/valid/labels.cache... 562 images, 38 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 562/562 214.3Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 6.5it/s 5.5s0.1s
                   all        562        786       0.81      0.806      0.828      0.498
Speed: 0.6ms preprocess, 5.9ms inference, 0.0ms loss, 0.8ms postprocess per image
Evaluating test set...
Ultralytics 8.4.174 🚀 Python-3.13.15 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
E_EAF_YOLO11n summary (fused): 180 layers, 2,720,760 parameters, 0 gradients, 10.6 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 3040.3±1881.1 MB/s, size: 162.9 KB)
val: Scanning /kaggle/working/E_EAF_YOLO11n/dataset/test/labels... 280 images, 19 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 280/280 1.3Kit/s 0.2s<0.0s
val: New cache created: /kaggle/working/E_EAF_YOLO11n/dataset/test/labels.cache
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 18/18 4.6it/s 4.0s0.1s
                   all        280        368      0.838      0.821      0.842      0.515
Speed: 1.4ms preprocess, 6.6ms inference, 0.0ms loss, 1.6ms postprocess per image
Results saved to /kaggle/working/E_EAF_YOLO11n/results/evaluation/E_EAF_YOLO11n_test

================================
VALIDATION
================================

           Model Split  Precision  Recall   mAP50   mAP75  mAP50-95
0  E_EAF_YOLO11n   val     0.8103  0.8063  0.8282  0.5395    0.4981

================================
TEST
================================

           Model Split  Precision  Recall   mAP50   mAP75  mAP50-95
0  E_EAF_YOLO11n  test     0.8379  0.8208  0.8418  0.5522    0.5147

================================
PER-CLASS TEST METRICS
================================

           class  Precision  Recall      F1    AP50  AP50-95
0         baekra     0.9159  1.0000  0.9561  0.9782   0.6969
1   color issues     0.7929  0.7298  0.7601  0.7719   0.4115
2  contamination     0.8801  0.9412  0.9096  0.9623   0.5301
3            cut     0.6697  0.7021  0.6855  0.5985   0.3840
4    gray stitch     0.8035  0.6815  0.7375  0.7659   0.4897
5         selvet     0.8894  0.7759  0.8288  0.8861   0.5326
6          stain     0.9136  0.9150  0.9143  0.9300   0.5581

In [48]:
# ============================================================
# CELL 12 — MODEL COMPLEXITY
# ============================================================

fresh = YOLO(
    str(BEST)
).model.float().cpu().eval()


params_m = (
    sum(
        p.numel()
        for p in fresh.parameters()
    )
    / 1e6
)


try:

    gflops = get_flops(
        fresh,
        640
    )

except Exception:

    gflops = float("nan")


size_mb = (
    BEST.stat().st_size
    / 2**20
)


del fresh


for row in (
    val_row,
    test_row
):

    row.update({

        "Params(M)": params_m,

        "GFLOPs": gflops,

        "Size(MB)": size_mb,

    })


summary = pd.DataFrame([
    val_row,
    test_row
]).round(4)


print("================================")
print("MODEL SUMMARY")
print("================================")

display(summary)


summary.to_csv(
    RES_DIR
    / f"{TAG}_summary.csv",
    index=False
)


test_pc.to_csv(
    RES_DIR
    / f"{TAG}_per_class_test.csv",
    index=False
)


print(
    "Results saved to:",
    RES_DIR
)

================================
MODEL SUMMARY
================================

,Model,Split,Precision,Recall,mAP50,mAP75,mAP50-95,Params(M),GFLOPs,Size(MB)
0,E_EAF_YOLO11n,val,0.8103,0.8063,0.8282,0.5395,0.4981,2.7287,10.7831,5.6392
1,E_EAF_YOLO11n,test,0.8379,0.8208,0.8418,0.5522,0.5147,2.7287,10.7831,5.6392

Results saved to: /kaggle/working/E_EAF_YOLO11n/results

In [44]:
# ============================================================
# CELL 13 — CONFIDENCE THRESHOLD SWEEP
# ============================================================

model = YOLO(
    str(BEST)
)


thresholds = [

    0.10,
    0.15,
    0.20,
    0.25,
    0.30,
    0.35,
    0.40,
    0.45,
    0.50,
    0.55,
    0.60,

]


threshold_rows = []


for conf in thresholds:

    print(
        f"Testing confidence = {conf}"
    )

    r = model.val(

        data=str(DATA_YAML),

        split="val",

        imgsz=640,

        batch=16,

        conf=conf,

        iou=0.7,

        device=0,

        plots=False,

        verbose=False,

    )


    precision = float(
        r.box.mp
    )

    recall = float(
        r.box.mr
    )


    if precision + recall > 0:

        f1 = (
            2
            * precision
            * recall
            /
            (precision + recall)
        )

    else:

        f1 = 0.0


    threshold_rows.append({

        "Confidence": conf,

        "Precision": precision,

        "Recall": recall,

        "F1": f1,

    })


threshold_df = pd.DataFrame(
    threshold_rows
)


print("\n================================")
print("CONFIDENCE RESULTS")
print("================================")

display(
    threshold_df.round(4)
)


# ------------------------------------------------------------
# Best F1
# ------------------------------------------------------------

best_f1_row = threshold_df.loc[
    threshold_df["F1"].idxmax()
]


# ------------------------------------------------------------
# Highest precision
# ------------------------------------------------------------

best_precision_row = threshold_df.loc[
    threshold_df["Precision"].idxmax()
]


print("\n================================")
print("BEST F1 THRESHOLD")
print("================================")

display(
    pd.DataFrame(
        [best_f1_row]
    ).round(4)
)


print("\n================================")
print("HIGHEST PRECISION THRESHOLD")
print("================================")

display(
    pd.DataFrame(
        [best_precision_row]
    ).round(4)
)


BEST_CONF = float(
    best_f1_row["Confidence"]
)


threshold_df.to_csv(
    RES_DIR
    / f"{TAG}_confidence_sweep.csv",
    index=False
)


print(
    "\nRecommended confidence based on validation F1:",
    BEST_CONF
)

Testing confidence = 0.1
Ultralytics 8.4.174 🚀 Python-3.13.15 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
E_EAF_YOLO11n summary (fused): 180 layers, 2,720,760 parameters, 0 gradients, 10.6 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 1943.5±771.1 MB/s, size: 64.3 KB)
val: Scanning /kaggle/working/E_EAF_YOLO11n/dataset/valid/labels.cache... 562 images, 38 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 562/562 147.3Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 7.0it/s 5.2s0.1s
                   all        562        786       0.81      0.806      0.805      0.484
Speed: 0.7ms preprocess, 5.4ms inference, 0.0ms loss, 0.8ms postprocess per image
Testing confidence = 0.15
Ultralytics 8.4.174 🚀 Python-3.13.15 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
E_EAF_YOLO11n summary (fused): 180 layers, 2,720,760 parameters, 0 gradients, 10.6 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 1619.5±1024.2 MB/s, size: 93.5 KB)
val: Scanning /kaggle/working/E_EAF_YOLO11n/dataset/valid/labels.cache... 562 images, 38 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 562/562 181.3Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 6.7it/s 5.4s0.1s
                   all        562        786       0.81      0.806        0.8       0.48
Speed: 0.7ms preprocess, 5.3ms inference, 0.0ms loss, 0.8ms postprocess per image
Testing confidence = 0.2
Ultralytics 8.4.174 🚀 Python-3.13.15 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
E_EAF_YOLO11n summary (fused): 180 layers, 2,720,760 parameters, 0 gradients, 10.6 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 2423.0±1446.8 MB/s, size: 762.2 KB)
val: Scanning /kaggle/working/E_EAF_YOLO11n/dataset/valid/labels.cache... 562 images, 38 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 562/562 181.3Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 6.9it/s 5.2s0.1s
                   all        562        786       0.81      0.806      0.776      0.471
Speed: 0.7ms preprocess, 5.4ms inference, 0.0ms loss, 0.8ms postprocess per image
Testing confidence = 0.25
Ultralytics 8.4.174 🚀 Python-3.13.15 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
E_EAF_YOLO11n summary (fused): 180 layers, 2,720,760 parameters, 0 gradients, 10.6 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 2146.8±997.2 MB/s, size: 106.9 KB)
val: Scanning /kaggle/working/E_EAF_YOLO11n/dataset/valid/labels.cache... 562 images, 38 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 562/562 168.4Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 6.8it/s 5.3s0.1s
                   all        562        786       0.81      0.806       0.77      0.467
Speed: 0.7ms preprocess, 5.4ms inference, 0.0ms loss, 0.8ms postprocess per image
Testing confidence = 0.3
Ultralytics 8.4.174 🚀 Python-3.13.15 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
E_EAF_YOLO11n summary (fused): 180 layers, 2,720,760 parameters, 0 gradients, 10.6 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 2155.0±1133.3 MB/s, size: 89.5 KB)
val: Scanning /kaggle/working/E_EAF_YOLO11n/dataset/valid/labels.cache... 562 images, 38 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 562/562 181.3Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 6.8it/s 5.3s0.1s
                   all        562        786      0.807      0.809      0.767      0.466
Speed: 0.7ms preprocess, 5.4ms inference, 0.0ms loss, 0.8ms postprocess per image
Testing confidence = 0.35
Ultralytics 8.4.174 🚀 Python-3.13.15 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
E_EAF_YOLO11n summary (fused): 180 layers, 2,720,760 parameters, 0 gradients, 10.6 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 2278.2±1318.2 MB/s, size: 103.0 KB)
val: Scanning /kaggle/working/E_EAF_YOLO11n/dataset/valid/labels.cache... 562 images, 38 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 562/562 214.3Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 6.8it/s 5.3s0.1s
                   all        562        786      0.808      0.803      0.756      0.459
Speed: 0.7ms preprocess, 5.4ms inference, 0.0ms loss, 0.8ms postprocess per image
Testing confidence = 0.4
Ultralytics 8.4.174 🚀 Python-3.13.15 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
E_EAF_YOLO11n summary (fused): 180 layers, 2,720,760 parameters, 0 gradients, 10.6 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 2056.7±1038.4 MB/s, size: 98.6 KB)
val: Scanning /kaggle/working/E_EAF_YOLO11n/dataset/valid/labels.cache... 562 images, 38 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 562/562 168.4Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 6.7it/s 5.4s0.1s
                   all        562        786      0.818      0.785      0.742      0.453
Speed: 0.7ms preprocess, 5.4ms inference, 0.0ms loss, 0.8ms postprocess per image
Testing confidence = 0.45
Ultralytics 8.4.174 🚀 Python-3.13.15 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
E_EAF_YOLO11n summary (fused): 180 layers, 2,720,760 parameters, 0 gradients, 10.6 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 1906.6±643.0 MB/s, size: 71.9 KB)
val: Scanning /kaggle/working/E_EAF_YOLO11n/dataset/valid/labels.cache... 562 images, 38 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 562/562 18.1Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 6.8it/s 5.3s0.1s
                   all        562        786      0.837      0.771       0.73      0.447
Speed: 0.7ms preprocess, 5.4ms inference, 0.0ms loss, 0.8ms postprocess per image
Testing confidence = 0.5
Ultralytics 8.4.174 🚀 Python-3.13.15 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
E_EAF_YOLO11n summary (fused): 180 layers, 2,720,760 parameters, 0 gradients, 10.6 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 2137.6±763.9 MB/s, size: 89.4 KB)
val: Scanning /kaggle/working/E_EAF_YOLO11n/dataset/valid/labels.cache... 562 images, 38 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 562/562 196.4Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 6.7it/s 5.4s0.1s
                   all        562        786      0.858       0.75      0.712      0.438
Speed: 0.7ms preprocess, 5.4ms inference, 0.0ms loss, 0.7ms postprocess per image
Testing confidence = 0.55
Ultralytics 8.4.174 🚀 Python-3.13.15 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
E_EAF_YOLO11n summary (fused): 180 layers, 2,720,760 parameters, 0 gradients, 10.6 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 1803.6±743.4 MB/s, size: 94.5 KB)
val: Scanning /kaggle/working/E_EAF_YOLO11n/dataset/valid/labels.cache... 562 images, 38 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 562/562 196.4Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 6.8it/s 5.3s0.1s
                   all        562        786       0.86      0.726      0.692      0.426
Speed: 0.7ms preprocess, 5.4ms inference, 0.0ms loss, 0.8ms postprocess per image
Testing confidence = 0.6
Ultralytics 8.4.174 🚀 Python-3.13.15 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
E_EAF_YOLO11n summary (fused): 180 layers, 2,720,760 parameters, 0 gradients, 10.6 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 1671.1±653.1 MB/s, size: 83.2 KB)
val: Scanning /kaggle/working/E_EAF_YOLO11n/dataset/valid/labels.cache... 562 images, 38 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 562/562 196.4Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 36/36 6.8it/s 5.3s0.1s
                   all        562        786      0.875        0.7       0.67      0.414
Speed: 0.7ms preprocess, 5.4ms inference, 0.0ms loss, 0.8ms postprocess per image

================================
CONFIDENCE RESULTS
================================

    Confidence  Precision  Recall      F1
0         0.10     0.8103  0.8063  0.8083
1         0.15     0.8103  0.8063  0.8083
2         0.20     0.8103  0.8063  0.8083
3         0.25     0.8103  0.8063  0.8083
4         0.30     0.8073  0.8086  0.8079
5         0.35     0.8079  0.8031  0.8055
6         0.40     0.8177  0.7846  0.8008
7         0.45     0.8368  0.7708  0.8024
8         0.50     0.8583  0.7503  0.8007
9         0.55     0.8596  0.7261  0.7873
10        0.60     0.8753  0.6995  0.7776

================================
BEST F1 THRESHOLD
================================

   Confidence  Precision  Recall      F1
0         0.1     0.8103  0.8063  0.8083

================================
HIGHEST PRECISION THRESHOLD
================================

    Confidence  Precision  Recall      F1
10         0.6     0.8753  0.6995  0.7776

Recommended confidence based on validation F1: 0.1

In [45]:
# ============================================================
# CELL 14 — FINAL MODEL
# ============================================================

FINAL_DIR = (
    WORK_ROOT
    / "final_model"
)

FINAL_DIR.mkdir(
    parents=True,
    exist_ok=True
)


FINAL_BEST = (
    FINAL_DIR
    / "best.pt"
)

FINAL_LAST = (
    FINAL_DIR
    / "last.pt"
)


shutil.copy2(
    BEST,
    FINAL_BEST
)


if LAST.exists():

    shutil.copy2(
        LAST,
        FINAL_LAST
    )


# ------------------------------------------------------------
# Save model metadata
# ------------------------------------------------------------

metadata = {

    "model": TAG,

    "best_model": str(
        FINAL_BEST
    ),

    "confidence_for_deployment": BEST_CONF,

    "imgsz": 640,

    "epochs": EPOCHS,

    "seed": SEED,

    "classes": names,

    "validation_metrics": val_row,

    "test_metrics": test_row,

}


with open(
    FINAL_DIR / "model_info.json",
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        metadata,
        f,
        indent=2
    )


print("================================")
print("FINAL MODEL")
print("================================")

print(
    "best.pt:",
    FINAL_BEST
)

print(
    "last.pt:",
    FINAL_LAST
)

print(
    "Recommended confidence:",
    BEST_CONF
)

================================
FINAL MODEL
================================
best.pt: /kaggle/working/E_EAF_YOLO11n/final_model/best.pt
last.pt: /kaggle/working/E_EAF_YOLO11n/final_model/last.pt
Recommended confidence: 0.1

In [47]:
# ============================================================
# CELL 15 — SAMPLE PREDICTION
# ============================================================

test_image_dir = (
    DATASET_DIR
    / test_name
    / "images"
)


test_images = [

    p for p in test_image_dir.glob("*")

    if p.suffix.lower()
    in IMAGE_EXTS

]


print(
    "Test images found:",
    len(test_images)
)


if len(test_images) > 0:

    sample_image = test_images[0]

    predictor = YOLO(
        str(FINAL_BEST)
    )


    results = predictor.predict(

        source=str(
            sample_image
        ),

        imgsz=640,

        conf=BEST_CONF,

        device=0,

        save=True,

        project=str(
            RES_DIR / "prediction"
        ),

        name="sample",

        exist_ok=True,

        verbose=False,

    )


    print(
        "Prediction completed."
    )

    print(
        "Image:",
        sample_image
    )

else:

    print(
        "No test image found."
    )

Test images found: 280
Results saved to /kaggle/working/E_EAF_YOLO11n/results/prediction/sample
Prediction completed.
Image: /kaggle/working/E_EAF_YOLO11n/dataset/test/images/IMG-20231009-WA0077_jpg.rf.5a5beddb2740a35dfec9608548eb58ca.jpg

In [49]:
# ============================================================
# CELL 16 — PACKAGE FINAL OUTPUT
# ============================================================

PACKAGE_DIR = (
    Path("/kaggle/working")
    / f"{TAG}_FINAL"
)


if PACKAGE_DIR.exists():

    shutil.rmtree(
        PACKAGE_DIR
    )


PACKAGE_DIR.mkdir(
    parents=True
)


# ------------------------------------------------------------
# Model
# ------------------------------------------------------------

shutil.copytree(

    FINAL_DIR,

    PACKAGE_DIR / "model",

    dirs_exist_ok=True

)


# ------------------------------------------------------------
# Results
# ------------------------------------------------------------

if RES_DIR.exists():

    shutil.copytree(

        RES_DIR,

        PACKAGE_DIR / "results",

        dirs_exist_ok=True

    )


# ------------------------------------------------------------
# Data configuration
# ------------------------------------------------------------

shutil.copy2(

    DATA_YAML,

    PACKAGE_DIR / "data.yaml"

)


# ------------------------------------------------------------
# Create ZIP
# ------------------------------------------------------------

archive = shutil.make_archive(

    str(
        Path("/kaggle/working")
        / TAG
    ),

    "zip",

    root_dir=PACKAGE_DIR.parent,

    base_dir=PACKAGE_DIR.name

)


print("============================================")
print("              TRAINING COMPLETE")
print("============================================")

print(
    "Best model:",
    FINAL_BEST
)

print(
    "ZIP:",
    archive
)

print(
    "Results:",
    RES_DIR
)

print(
    "Best F1 confidence:",
    BEST_CONF
)

print("============================================")

============================================
              TRAINING COMPLETE
============================================
Best model: /kaggle/working/E_EAF_YOLO11n/final_model/best.pt
ZIP: /kaggle/working/E_EAF_YOLO11n.zip
Results: /kaggle/working/E_EAF_YOLO11n/results
Best F1 confidence: 0.1
============================================